CREATE TABLE [dbo].[clients](
	[client_id] [int] NOT NULL,
	[fac_id] [int] NOT NULL,
	[deleted] [varchar](1) NOT NULL,
	[created_by] [varchar](60) NOT NULL,
	[created_date] [datetime] NOT NULL,
	[revision_by] [varchar](60) NULL,
	[revision_date] [datetime] NULL,
	[external_sync_code] [varchar](50) NULL,
	[current_census_id] [int] NULL,
	[client_id_number] [varchar](35) NULL,
	[chart_number] [int] NULL,
	[admission_date] [datetime] NULL,
	[discharge_date] [datetime] NULL,
	[comments] [varchar](254) NULL,
	[out_patient] [char](1) NULL,
	[pharmacy_id] [int] NULL,
	[pharm_ad_rec_sent] [datetime] NULL,
	[pharm_dis_rec_sent] [datetime] NULL,
	[next_quarterly_assess_date] [datetime] NULL,
	[next_full_assess_date] [datetime] NULL,
	[next_medicare_assess_date] [datetime] NULL,
	[next_medicare_type] [int] NULL,
	[medicare_admission_date] [datetime] NULL,
	[last_physician_visit] [datetime] NULL,
	[next_physician_visit] [datetime] NULL,
	[current_care_plan_id] [int] NULL,
	[DELETED_BY] [varchar](60) NULL,
	[DELETED_DATE] [datetime] NULL,
	[primary_physician_id] [int] NULL,
	[bmi] [varchar](50) NULL,
	[original_admission_date] [datetime] NULL,
	[medicare_reentry_date] [datetime] NULL,
	[case_manager_id] [int] NULL,
	[transfer_date] [datetime] NULL,
	[locked_date] [datetime] NULL,
	[reassessment_interval] [int] NULL,
	[locked_by] [varchar](60) NULL,
	[closed_by] [varchar](60) NULL,
	[closed_date] [datetime] NULL,
	[closed_reason] [varchar](50) NULL,
	[photo] [varchar](50) NULL,
	[classification] [varchar](25) NULL,
	[interpreter_needed] [char](1) NULL,
	[photo_date] [datetime] NULL,
	[photo_small] [varchar](55) NULL,
	[prod_client_id] [int] NULL,
	[nickname] [varchar](50) NULL,
	[mpi_id] [int] NULL,
	[next_mmq_date] [datetime] NULL,
	[initial_admission_date] [datetime] NULL,
	[legal_address] [char](1) NULL,
	[current_rate_id] [int] NULL,
	[estimated_discharge_date] [datetime] NULL,
	[last_review_date] [datetime] NULL,
	[next_review_date] [datetime] NULL,
	[pending_date] [datetime] NULL,
	[waiting_list_flag] [char](1) NULL,
	[date_requested] [datetime] NULL,
	[desired_move_date] [datetime] NULL,
	[desired_bed_id] [int] NULL,
	[deposit_amount] [money] NULL,
	[next_quarterly_type] [tinyint] NULL,
	[mar_start_date] [smalldatetime] NULL,
	[is_allergy_determined] [bit] NOT NULL,
	[waiting_room_type] [int] NULL,
	[balexp_unpaid_balance] [money] NULL,
	[balexp_unpaid_balance_date] [datetime] NULL,
	[client_uuid] [uniqueidentifier] NULL,
	[rr_census_rate_change_date] [datetime] NULL
)