CREATE TABLE [dbo].[wv_vitals](
	[vitals_id] [int] NOT NULL,
	[fac_id] [int] NOT NULL,
	[created_by] [varchar](60) NOT NULL,
	[created_date] [datetime] NOT NULL,
	[revision_by] [varchar](60) NULL,
	[revision_date] [datetime] NULL,
	[std_vitals_id] [int] NOT NULL,
	[client_id] [int] NOT NULL,
	[date] [datetime] NOT NULL,
	[pn_id] [int] NULL,
	[value] [float] NULL,
	[baseline] [varchar](2) NULL,
	[dystolic_value] [float] NULL,
	[type_id] [int] NULL,
	[strikeout_flag] [char](1) NOT NULL,
	[strikeout_id] [int] NULL,
	[strikeout_by] [varchar](60) NULL,
	[strikeout_date] [datetime] NULL,
	[equipment_flag] [bit] NOT NULL,
	[observer_identifier] [varchar](80) NULL,
	[observer_first_name] [varchar](100) NULL,
	[observer_last_name] [varchar](100) NULL,
	[o2_concentration_value] [int] NULL,
	[o2_flow_rate_value] [int] NULL,
	[head_circumference_percentile] [int] NULL,
	[bmi_percentile] [int] NULL,
	[weight_for_length_percentile] [int] NULL
)